### ISSUE TITLE
Display Name saves as null in firebase

### ISSUE THREAD

**Issue by nelsons-handle** [Xanathar-Guild/arcane-focus-web#4]
<img width="1378" alt="Screenshot 2023-09-05 at 7 16 12 PM" src="https://github.com/Xanathar-Guild/arcane-focus-web/assets/13908992/739b6034-275b-49be-b3e7-7f4133d01acd">

On registration, name does not seem to have a purpose. 
1. It should show on Profile & Dashboard, at minimum, instead of or paired with email. 
2. `displayName` should not save as `null` and should instead be saved for future use.

**Comment by chrisheckey** [comment]
🤔

**Comment by nelsons-handle** [comment]
This is more like a Bug & Feature request. 
Trying to hook into `currentUser.name` or `currentUser.displayName` returns `null`

<img width="1011" alt="Screenshot 2023-09-05 at 8 37 37 PM" src="https://github.com/Xanathar-Guild/arcane-focus-web/assets/13908992/5096c41c-1ef6-46e3-b0a7-b7115a87b3b6">

**Comment by chrisheckey** [comment]
@nelsons-handle seems firebase requires a second request to update the displayName in firebase auth
